name: build

on: 
  push:
    branches:
      -master
  pull_request:
    branches:
      -master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301

    - name: Install dependencies
      run: dotnet restore
      working-directory: C#\Team7-Codes.sln

    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: C#\Team7-Codes.sln

    - name: Test
      run: dotnet test --no-restore --verbosity normal --collect:"XPlat Code Coverage"
      working-directory: C#\Team7-Codes.sln

    - name: Publish code coverage reports to codecove.io
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.379f118e-8d4a-48a6-8189-4b88f201309b }}
        files: ./**/coverage.cobertura.xml
        fail_ci_if_error: true
